version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
         MYSQL_DATABSE: courses_db
         MYSQL_USER: courses
         MYSQL_PASSWORD: c0urse1234
         MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306



